[package]
name = "cosmic-applet-privacy"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[[bin]]
name = "cosmic-applet-privacy"
path = "src/main.rs"

[lib]
name = "cosmic_applet_privacy"
path = "src/lib.rs"

[dependencies]
cosmic-time.workspace = true
futures.workspace = true
glob = "0.3"
i18n-embed-fl.workspace = true
i18n-embed.workspace = true
libcosmic.workspace = true
pipewire = "0.9"
rust-embed.workspace = true
rustc-hash.workspace = true
tokio.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
